= Primitive Deque Types
:srcDir: src/main/kotlin/io/foxcapades/lib/pdk

image:https://img.shields.io/github/license/Foxcapades/pdk[]
image:https://img.shields.io/badge/jdk-1.8-blue[]
image:https://img.shields.io/badge/docs-dokka-darkgreen[link="https://foxcapades.github.io/pdk/dokka/"]
image:https://img.shields.io/maven-central/v/io.foxcapades.lib/pdk[Maven Central, link="https://search.maven.org/search?q=g:io.foxcapades.lib%20AND%20a:pdk"]

Simple library that provides Deque implementations for all Kotlin's primitive
types that deal in unboxed values.

== Usage

.`*build.gradle.kts*`
[source, kotlin]
----
dependencies {
  implementation("io.foxcapades.lib:pdk:1.0.0")
}
----

== Provided Types

* link:{srcDir}/BooleanDeque.kt[`BooleanDeque`]
* link:{srcDir}/CharDeque.kt[`CharDeque`]
* link:{srcDir}/ByteDeque.kt[`ByteDeque`]
* link:{srcDir}/ShortDeque.kt[`ShortDeque`]
* link:{srcDir}/IntDeque.kt[`IntDeque`]
* link:{srcDir}/LongDeque.kt[`LongDeque`]
* link:{srcDir}/FloatDeque.kt[`FloatDeque`]
* link:{srcDir}/DoubleDeque.kt[`DoubleDeque`]
* link:{srcDir}/UByteDeque.kt[`UByteDeque`]
* link:{srcDir}/UShortDeque.kt[`UShortDeque`]
* link:{srcDir}/UIntDeque.kt[`UIntDeque`]
* link:{srcDir}/ULongDeque.kt[`ULongDeque`]

== Development

As all the types in this library are identical apart for the primitive type they
deal in, the code for most files is generated based on the contents of the
link:{srcDir}/ByteDeque.kt[`ByteDeque`] file.

To modify this library, the only source files that should be manually edited are
the base type, link:{srcDir}/PrimitiveDeque.kt[`PrimitiveDeque`], and the
implementation type, link:{srcDir}/ByteDeque.kt[`ByteDeque`].

After the adjustments are made to those two files, the remaining files can be
generated by calling `make clone-deques`.

=== The Base Type

This contains a singular, abstract base class,
link:{srcDir}/PrimitiveDeque.kt[`PrimitiveDeque`], that defines what shared
functionality can be defined without dealing in generics, and thus, primitive
boxing.  This type _does_ take generic parameters, however those are used
exclusively to define the JDK interop functions that, sadly, must deal in boxed
values.  An example of one such method is `iterator()` defined by the generic
type `Iterable<V>`.